error: "Ошибка"
success: "Успешно"

noPerm: "У тебя нет необходимых разрешений для использования этой команды!"
botError: "Ты не можешь применять команды к ботам!"
userNotFound: "Пользователь не найден!"

trackError.title: "Неудалось загрузить трек"
trackError.desc: "Вы ввели неверную ссылку или видео недоступно: {}"